services:
  server:
    container_name: node-server
    image: node-server:0.0.1
    env_file:
      - .env.development
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/server/src
    expose:
      - 4000
    ports:
      - 4000:4000
    command: yarn dev
