services:
  db:
    container_name: psql-db
    image: postgres:15.3-alpine
    env_file:
      - .env
    restart: always
    volumes:
      - test-db:/db
    ports:
      - ${DB_PORT}:${DB_PORT}
volumes:
  test-db:
